---
- name: Update and reboot
  hosts: 192.168.1.97
  gather_facts: no
  tasks:
 #  - name: Upgrade all packages
  #   yum:
   #    name: '*'
    #   state: latest
       
   - name: Reboot servers
     reboot:
       pre_reboot_delay: 90
       msg: "Server will be rebooted in 90 seconds."
...
